/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Cast_votesContract } from "./Cast_votes";
import { CastVotesContract } from "./CastVotes";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "cast_votes"): Cast_votesContract;
      require(name: "CastVotes"): CastVotesContract;
    }
  }
}

export { Cast_votesContract, Cast_votesInstance } from "./Cast_votes";
export { CastVotesContract, CastVotesInstance } from "./CastVotes";
